### ISSUE TITLE
Please tell me the reference paper

### ISSUE THREAD

**Issue by jiaoxiang1996** [bitscott1102/Automatic-modulation-classification-by-decision-tree-based-on-features-extraction#1]
Please

**Comment by bitscott1102** [comment]
Hi there, the papers that I referenced are:

1. Delving Deep into Rectifiers: Surpassing Human-Level Performance on ImageNet Classification, Kaiming He, Xiangyu Zhang, Shaoqing Ren, Jian Sun

3. 张鸣. 软件无线电接收机中信号调制样式识别算法的研究[D]. 西安科技大学, 2005.

The thresholds are listed as following. However, it depends on the single(the range of amplitude...), what kind of noise you add, etc. In my case, I just plot the pictures and set a clear threshold. In some cases, I want the separation to be clear in the signal with lower SNR, while some may be higher SNR. So the thresholds vary cases to cases.

$$
t\left(m_{11}\right)=0.301 ;
\\t\left(m_{12}\right)=0.2345 ; 
\\t\left(m_{2}\right)=0.306 ;
\\t\left(m f_{1}\right)=0.21015 ;
\\t\left(mf_{2}\right)=0.4226 ; 
\\ t\left(m p_{1}\right) =0.43505
$$
